apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bo0ntpbuu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bo0ntpbuu-go 
  name: bo0ntpbuu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bo0ntpbuu-go 
